import type { Hole, Round } from '../types';
import { parDiffLabel, scoreLabel } from '../utils/golf';
import { NumberStepper } from './NumberStepper';
import { ParScoreStepper } from './ParScoreStepper';
interface Props{displayName:string;round:Round;holeIndex:number;saveStatus:'idle'|'saving'|'saved'|'error';onUpdateHole:(index:number,patch:Partial<Hole>)=>void;onGoToHole:(i:number)=>void;onFinish:()=>void;onViewScorecard:()=>void;onExit:()=>void;onForceTerminate:()=>void;}
export function HoleEntry({displayName,round,holeIndex,saveStatus,onUpdateHole,onGoToHole,onFinish,onViewScorecard,onExit,onForceTerminate}:Props){const hole=round.holes[holeIndex],last=holeIndex===round.holes.length-1,label=scoreLabel(hole.score,hole.par);const total=round.holes.slice(0,holeIndex+1).reduce((s,h)=>s+(h.score||0),0);const par=round.holes.slice(0,holeIndex+1).reduce((s,h)=>s+h.par,0);return <div className="round-screen flex flex-1 flex-col overflow-y-auto pb-6">
<header className="round-topbar"><button onClick={()=>holeIndex>0?onGoToHole(holeIndex-1):onExit()}>← 이전 홀</button><div><b>{hole.number}번 홀</b><small>(PAR {hole.par})</small></div><button onClick={()=>last?onFinish():onGoToHole(holeIndex+1)}>{last?'완료':'다음 홀 →'}</button></header>
<main className="round-content">
<section className="course-visual glass-card"><div className="hole-map"><span>{hole.number}</span></div><div className="course-info"><b>{round.courseName}</b><dl><div><dt>PAR</dt><dd>{hole.par}</dd></div><div><dt>거리</dt><dd>{hole.distance??'-'} m</dd></div><div><dt>코스</dt><dd>{round.courseCourseName||round.teeBox||'A코스'}</dd></div></dl></div></section>
<button type="button" onClick={onViewScorecard} className="glass-card mt-3 w-full py-2.5 text-center text-xs font-bold text-emerald-700">▤ 전체 스코어카드 보기</button>
<section className="player-score-card glass-card"><div className="player-title"><span className="avatar-dot">◉</span><b>{displayName} (나) <em>♛</em></b><span>{saveText(saveStatus)}</span></div><div className="score-main"><ParScoreStepper hole={hole} onChange={v=>onUpdateHole(holeIndex,{score:v})}/><div className="score-side"><div><small>누적</small><b>{total}</b></div><div className="diff"><small>전체 파 대비</small><b>{parDiffLabel(total,par)}</b></div></div></div>{label&&<div className="score-label">{label}</div>}</section>
<section className="glass-card input-card"><div className="input-head"><b>▣ 메모 (선택)</b><small>{(hole.notes||'').length}/100</small></div><textarea value={hole.notes||''} maxLength={100} onChange={e=>onUpdateHole(holeIndex,{notes:e.target.value})} placeholder="이 홀에 대한 메모를 입력하세요.\n(예: 잘 맞은 티샷, 아쉬운 퍼팅 등)"/></section>
<section className="glass-card input-card"><div className="input-head"><b>◎ 샷 기록</b></div>{hole.par!==3&&<div className="shot-row"><span>페어웨이 적중</span><div><button onClick={()=>onUpdateHole(holeIndex,{fairway:'hit'})} className={hole.fairway==='hit'?'selected':''}>성공</button><button onClick={()=>onUpdateHole(holeIndex,{fairway:'miss'})} className={hole.fairway==='miss'?'selected dark':''}>실패</button></div></div>}<div className="shot-row"><span>GIR (그린 적중)</span><div><button onClick={()=>onUpdateHole(holeIndex,{gir:true})} className={hole.gir===true?'selected':''}>성공</button><button onClick={()=>onUpdateHole(holeIndex,{gir:false})} className={hole.gir===false?'selected dark':''}>실패</button></div></div></section>
<section className="putt-card glass-card"><NumberStepper value={hole.putts} onChange={v=>onUpdateHole(holeIndex,{putts:v})} min={0} max={10} size="sm" label="퍼팅"/></section>
<button onClick={last?onFinish:()=>onGoToHole(holeIndex+1)} className="next-hole-cta">{last?'라운드 종료':'다음 홀 이동 →'}</button>
<div className="round-actions"><button onClick={onExit}>▣ <span>임시 저장<small>홈으로 이동</small></span></button><button onClick={onForceTerminate} className="exit-danger">⇥ <span>나가기<small>기록 삭제하고 종료</small></span></button></div>
<div className="progress-card glass-card"><div><b>전체 진행 상황</b><strong>{holeIndex+1} / {round.holeCount}홀</strong></div><i><span style={{width:`${((holeIndex+1)/round.holeCount)*100}%`}}/></i></div>
</main></div>}
function saveText(s:Props['saveStatus']){return s==='saving'?'저장 중...':s==='saved'?'저장 완료 ✓':s==='error'?'저장 실패':'자동 저장'}
