import type { ParkPlayer, Round } from '../types';
import { NumberStepper } from './NumberStepper';
interface Props { round: Round; holeIndex: number; saveStatus: 'idle'|'saving'|'saved'|'error'; onUpdateParkScore: (playerIndex: number, holeIndex: number, score: number) => void; onGoToHole: (i:number)=>void; onFinish:()=>void; onExit:()=>void; onForceTerminate:()=>void; onViewScorecard:()=>void; }
export function ParkHoleEntry({ round, holeIndex, saveStatus, onUpdateParkScore, onGoToHole, onFinish, onExit, onForceTerminate, onViewScorecard }: Props) {
  const players: ParkPlayer[] = round.parkPlayers?.length ? round.parkPlayers : [{ id: 'player-1', name: '나', scores: round.holes.map(h => h.score) }];
  const last = holeIndex === round.holeCount - 1;
  return <div className="flex flex-1 flex-col">
    <header className="flex h-14 items-center justify-between px-2"><div className="flex items-center gap-1"><button onClick={onExit} className="h-10 w-10 text-2xl text-gray-500">×</button><button onClick={onForceTerminate} className="rounded-lg px-2 py-1 text-xs font-bold text-red-500">나가기</button></div><span className="text-xs text-gray-500">{saveStatus==='saving'?'저장 중...':saveStatus==='saved'?'저장 완료 ✓':saveStatus==='error'?'저장 실패 · 연결 확인':''}</span><button onClick={onViewScorecard} className="text-sm font-bold text-emerald-700">전체 기록</button></header>
    <div className="flex flex-1 flex-col overflow-y-auto px-5 pb-5"><div className="py-5 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-50 text-3xl">🏌️</div><p className="mt-3 text-xs font-bold tracking-widest text-emerald-700">PARK GOLF</p><h1 className="mt-1 text-2xl font-bold">{holeIndex + 1}번 홀</h1><p className="mt-1 text-sm text-gray-400">{round.holeCount}홀 중 {holeIndex + 1}번째 · {players.length}명 기록</p></div>
      <div className="flex flex-col gap-3">{players.map((player, playerIndex) => <div key={player.id} className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><p className="font-bold text-gray-800">{player.isOwner ? '★ ' : ''}{player.name}</p><span className="text-xs text-emerald-600 font-bold">누적 {player.scores.slice(0,holeIndex).reduce((a,b)=>a+b,0)}타</span></div><NumberStepper value={player.scores[holeIndex] ?? 0} onChange={v => onUpdateParkScore(playerIndex, holeIndex, v)} min={0} max={20}/></div>)}</div>
    </div>
    <div className="flex gap-2 border-t border-gray-100 px-5 py-4"><button disabled={holeIndex===0} onClick={()=>void onGoToHole(holeIndex-1)} className="h-14 flex-1 rounded-xl bg-gray-100 font-semibold text-gray-700 disabled:opacity-40">이전 홀</button><button onClick={last?onFinish:()=>void onGoToHole(holeIndex+1)} className="h-14 flex-1 rounded-xl bg-emerald-600 font-bold text-white">{last?'라운드 종료':'다음 홀'}</button></div>
  </div>;
}
